config/routes.rb
CrServer::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users

  root :to => "ingredients#index"
  match "/d", to: "ingredients#index"
  match "/api", to: "api_documentation#index"
  
  resources :landing, only: [:index] do
    collection do
      post :signup
    end
  end

  devise_for :users

  resources :labels, only: [:create, :show] do
    member do
      put 'rate'
    end
  end

  resources :ingredients, only: [:index, :show, :edit, :update] do
    collection do
      get 'search'
      get 'proofread'
      get 'unwritten'
    end

    member do
      delete 'delete'
      put 'proof'
    end
  end

  resources :ingredient_of_the_weeks, only: [:index] do
    collection do
      get 'current'
    end
    member do
      put 'distribute'
    end
  end

  resources :resources, only: [:index] do
    member do
      get 'edit_ingredient'
      put 'update_ingredient'
    end
  end

  match "/sitemap.:format" => 'sitemap#sitemap'

  match '*path' => 'ingredients#index'

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  
  def index    
    @test_danger = (request.original_fullpath.match(/^\/d/))
  end

  def signup
    LandingSignup.create({email: params[:email]})
    render :status => 200, :json => {}
  end
  
end

app/views/landing/_ingredients.html.erb
<% if @test_danger %>
	<div class="item active">
		<div class='col-md-4 col-md-offset-1' id='example-name'>
			EDTA
		</div>
		<div class='col-md-6' id='example-description'>
			EDTA is a colorless crystalline acid that binds to iron, and used to fortify grain in breakfast cereal. Safe in small amounts.
		</div>
	</div>
	<div class="item">
		<div class='col-md-4 col-md-offset-1' id='example-name'>
			Xanthan Gum
		</div>
		<div class='col-md-6' id='example-description'>
			Xanthan gum is made from a chemical secreted by a bacterium, used to make food thicker and hold ingredients together.
		</div>
	</div>
	<div class="item">
		<div class='col-md-4 col-md-offset-1' id='example-name'>
			Yellow #5
		</div>
		<div class='col-md-6' id='example-description'>
			Yellow #5 is a synthetic food coloring common in commercial processed foods that appear green/yellow or brown and creamy.
		</div>
	</div>
<% else %>
	<div class="item active">
		<div class='col-md-4 col-md-offset-1' id='example-name'>
			Xanthan Gum
		</div>
		<div class='col-md-6' id='example-description'>
			Xanthan gum is made from a chemical secreted by a bacterium, used to make food thicker and hold ingredients together.
		</div>
	</div>
	<div class="item">
		<div class='col-md-4 col-md-offset-1' id='example-name'>
			Yellow #5
		</div>
		<div class='col-md-6' id='example-description'>
			Yellow #5 is a synthetic food coloring common in commercial processed foods that appear green/yellow or brown and creamy.
		</div>
	</div>
	<div class="item">
		<div class='col-md-4 col-md-offset-1' id='example-name'>
			Titanium Dioxide
		</div>
		<div class='col-md-6' id='example-description'>
			Titanium dioxide is a naturally occurring white pigment sourced from the mineral ilmenite, found in milk and sunscreen.
		</div>
	</div>
<% end %>

app/views/landing/index.html.erb
<div class='row' id='title-row'>
	<div class='col-md-2'>
		&nbsp;
	</div>
	<div class='col-md-8' id='top-logo'>
		<%= link_to image_tag("logo_horizontal.png", style: "width: 100%; max-width: 405px;"), ingredients_path %>
	</div>
	
	<div class='col-md-12 hidden-md hidden-lg' id='phone-spacer'>
		&nbsp;
	</div>
	
	<div class='col-md-2' id='sign-up'>
		<a href="#" class='btn btn-lg btn-success' id='btn-sign-up'>Sign Up</a>
	</div>	
</div>

<div class='row' id='signup-row'>
  <div class="col-md-4 col-md-offset-4">
	<div id='launching-soon'>We'll let you know when we launch!</div>
    <div class="input-group">
      <input type="text" class="form-control" id='email-sign-up' placeholder="Email">
      <span class="input-group-btn">
        <button class="btn btn-default btn-success" id='button-sign-up' type="button">Let me know</button>
      </span>
    </div><!-- /input-group -->
  </div>
</div>
<div class='alert alert-success' id='sign-up-success'>Thanks! We'll keep you updated.</div>

<div class='row class="carousel slide' data-ride="carousel" id='example-row'>
	
	<ol class="carousel-indicators">
		<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
		<li data-target="#carousel-example-generic" data-slide-to="1"></li>
		<li data-target="#carousel-example-generic" data-slide-to="2"></li>
	</ol>

  <div class="carousel-inner">
	<%= render partial: 'ingredients' %>	
  </div>

</div>

<div class='row' id='screenshot-row'>
	<div class='col-md-4 screenshot-column'>
		<div class='top-label'>
			Snap a photo.
			<div class='subtitle'>
				Take a picture of any ingredient label.<br/>&nbsp;		
			</div>
		</div>
		<div class='screenshot'>
			<%= image_tag "screenshot-photo.png", height: 300 %>
		</div>

	</div>
	<div class='col-md-4 screenshot-column'>
		<div class='top-label'>
			See what's inside.
			<div class='subtitle'>
				<% if @test_danger %>
					We show you the hazards of<br/>each ingredient.
				<% else %>
					We show you easy-to-understand<br/>definitions of each ingredient.				
				<% end %>

			</div>			
		</div>
		<div class='screenshot'>
			<%= image_tag "screenshot-results.png", height: 300 %>
		</div>
	</div>
	
	<div class='col-md-4 screenshot-column'>
		<div class='top-label'>
			Know your food.
			<div class='subtitle'>
				<% if @test_danger %>
					Avoid foods that are unsafe.<br/>&nbsp;
				<% else %>
					Feel confident in the food<br/>you're eating.
				<% end %>
				
			</div>
		</div>					
		<div class='screenshot'>
			<%= image_tag "screenshot-ingredient.png", height: 300 %>
		</div>
	</div>	
</div>