config/routes.rb
CrServer::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users

  root :to => "ingredients#index"
  match "/d", to: "ingredients#index"
  match "/api", to: "api_documentation#index"
  
  resources :landing, only: [:index] do
    collection do
      post :signup
    end
  end

  devise_for :users

  resources :labels, only: [:create, :show] do
    member do
      put 'rate'
    end
  end

  resources :ingredients, only: [:index, :show, :edit, :update] do
    collection do
      get 'search'
      get 'proofread'
      get 'unwritten'
    end

    member do
      delete 'delete'
      put 'proof'
    end
  end

  resources :ingredient_of_the_weeks, only: [:index] do
    collection do
      get 'current'
    end
    member do
      put 'distribute'
    end
  end

  resources :resources, only: [:index] do
    member do
      get 'edit_ingredient'
      put 'update_ingredient'
    end
  end

  match "/sitemap.:format" => 'sitemap#sitemap'

  match '*path' => 'ingredients#index'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :description, :name, :bulk_description, :visible, :proofed,
    :view_count

  has_many :matches
  has_many :labels, :through => :matches
  has_and_belongs_to_many :technical_effects
  has_and_belongs_to_many :regulatory_statuses
  has_and_belongs_to_many :resources
  validates_uniqueness_of :name

  #default_scope order("name ASC")
  scope :visible, -> { where(visible: true) }
  scope :not_proofed, -> { where(proofed: false) }
  scope :most_popular, -> { order("view_count DESC") }

  def self.name_list
    Ingredient.pluck(:name)
  end

  def to_s
    name
  end

  def technical_effects_string
    technical_effects.map{|te| te.name}.join(", ")
  end

  def path
    "/#{URI::encode(name)}"
  end

  def proofed!
    self.proofed = true
    save
  end

  def increment_view_count!
    self.view_count += 1
    self.save
  end

  def related
    related_ingredients = []

    related_ingredients << technical_effects.map do |te|
      te.ingredients.most_popular.limit(10)
    end

    related_ingredients.flatten!
    related_ingredients.delete(self)
    related_ingredients.uniq
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  load_and_authorize_resource

  def index
    @featured_ingredient = find_featured_ingredient(params[:path])
    @ingredients = Ingredient.visible.order("name ASC")
  end

  def show
    @ingredient.increment_view_count!
    render layout: false
  end

  def search
    name = params[:name]
    @ingredients = name.present? ? Ingredient.visible.where("name like ?", "%#{name}%").order("name ASC") : Ingredient.visible.most_popular.limit(20)

    name ||= ""

    @ingredients.sort!{|a,b|
        a.name.downcase.index(name.downcase) <=> b.name.downcase.index(name.downcase) }

    render layout: false
  end

  def unwritten
    @ingredients = Ingredient.where(bulk_description: true).order("name ASC")
    @ingredients = @ingredients.map{|i| i.technical_effects.any? ? i : nil}.compact
  end

  def edit
  end

  def update
    @ingredient.update_attributes(params[:ingredient])

    @ingredient.visible = true
    @ingredient.save

    redirect_to :action => :unwritten
  end

  def delete
    @ingredient.destroy
    redirect_to :action => :unwritten
  end

  def proofread
    page_length = 20
    @page = params[:page].to_i || 1

    @ingredients = Ingredient.visible.not_proofed.offset(@page * page_length).limit(page_length)
    @pages = (Ingredient.visible.not_proofed.count.to_f / 20.to_f).floor
  end

  def proof
    @ingredient = Ingredient.find(params[:id])
    @ingredient.update_attributes(params[:ingredient])
    @ingredient.proofed!

    redirect_to :action => :proofread
  end

  private

  def find_featured_ingredient(name)
    ingredient = Ingredient.find_by_name(name) if name
    ingredient ||= IngredientOfTheWeek.current.ingredient
    ingredient
  end

end

app/views/ingredients/_ingredient.html.erb
<div class='col-md-12 name'>
	<%= ingredient.name %>
</div>
<div class='col-md-12 technical-effects'>
	<%= ingredient.technical_effects.map{|te| te.name.downcase}.join(" | ") %>
</div>
<div class='col-md-12 description'>
	<%= ingredient.description %>
</div>
<div class='col-md-12 related-ingredients'>
	<%= render partial: "related", locals: {related_ingredients: ingredient.related} %>
</div>
<div class='col-md-12 share'>
	<a href="https://twitter.com/share" class="twitter-share-button" data-via="digestableapp">Tweet</a>
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</div>

<div class='col-md-12 footer-links text-center'>
	<%= link_to "API", "/api" %>
	|
	<%= link_to "Blog", "http://blog.digestable.co" %>
</div>

app/views/ingredients/_related.html.erb
<% if related_ingredients.any? %>
<div class='related-to'>
  See Also
</div>
<ul>
  <% related_ingredients.each do |related| %>
    <li>
      <%= link_to related.name, "#", class: 'related-ingredient',
        data_id: related.id, data_path: related.path %>
    </li>
  <% end %>
</ul>
<% end %>

app/views/ingredients/edit.html.erb
<%= @ingredient.technical_effects.map{|te| te.name }.join(", ") %><br/>
<%= @ingredient.regulatory_statuses.map{|te| te.name }.join(", ") %><br/>

<%= form_for(@ingredient) do |f| %>
<ul>
	<li>	
	<%= f.text_field :name %>
	</li>
	<li>
	<%= f.text_area :description %>
	</li>
	<li>
	<%= f.check_box :bulk_description %>
	</li>
	<li>
	<%= f.submit %>
	</li>
</ul>
<% end %>

app/views/ingredients/index.html.erb
<% content_for :title do %><%= @featured_ingredient %><% end %>

<% content_for :head do %>
	<meta name="description" content="<%= @featured_ingredient.description %>" />
	<meta property="og:title" content="<%= @featured_ingredient.name %>" />
	<meta property="og:description" content="<%= @featured_ingredient.description %>" />
	<meta property="og:url" content="http://digestable.co/<%=u @featured_ingredient.name %>" />
	<meta property="og:image" content="http://digestable.co/assets/og_preview_wide.png" />
<% end %>

<div class='row' id='ingredients'>
	<div class='col-md-3 visible-md visible-lg' id='ingredient-list'>
		<ul>
		<% Ingredient.visible.order("name ASC").each do |i| %>
			<li>
				<%= link_to i.name, i.path,
					class: 'list-ingredient',
					data_id: i.id, data_path: i.path %>
			</li>
		<% end %>
		</ul>
	</div>

	<div class='col-md-9 col-sm-12' id='ingredients-search-container'>
		<div class='row'>
			<div class='col-md-offset-3 col-md-6 col-sm-8 col-sm-offset-2' id='logo-container'>
				<div id='logo'>
					<%= image_tag "ingredient_logo.png", id: 'logo-img' %>
				</div>
			</div>

			<div class='col-md-offset-3 col-md-6 col-sm-8 col-sm-offset-2' id='search-bar-container'>
					<%= text_field_tag :something, nil,
						class: 'form-control search-bar',
						placeholder: "Search for ingredient" %>
			</div>

			<div class='col-md-offset-3 col-md-6 col-sm-8 col-sm-offset-2' id='search-results'>
			</div>

			<div class='col-md-offset-3 col-md-6 col-sm-8 col-sm-offset-2' id='ingredient'>
				<%= render partial: "ingredient",
					locals: {ingredient: @featured_ingredient}%>
			</div>
		</div>


	</div>
</div>

app/views/ingredients/proofread.html.erb
<h2>Not Proofred</h2>

<ul class="pagination">
	<% (1..@pages).each do |i| %>
		<li><%= link_to i, proofread_ingredients_path(page: i) %></li>
	<% end %>
</ul>

<ul id='proofed'>	
	<% @ingredients.each do |ingredient| %>
		<%= form_for(ingredient, url: proof_ingredient_path(ingredient)) do |f| %>
			<li class='row'>
				<div class='col-md-2'>
					<%= ingredient.id %>: <%= ingredient.name %>
				</div>
				<div class='col-md-8'>
					<%= f.text_area :description %>
				</div>
				<div class='col-md-2'>
					<%= f.submit "Update", class: "btn btn-success" %>
				</div>
			</li>
		<% end %>
	<% end %>
</ul>

app/views/ingredients/search.html.erb
<ul>
	<% @ingredients.first(5).each do |i| %>
		<li class='search-result' 
			data_id='<%= i.id %>', 
			data_path="<%= i.path %>">
			<%= i.name %>
		</li>
	<% end %>	
</ul>

app/views/ingredients/show.html.erb
<%= render partial: "ingredient", locals: {ingredient: @ingredient} %>

app/views/ingredients/unwritten.html.erb
<h1><%= @ingredients.count %> of <%= Ingredient.count %></h1>

<table class='table table-striped'>
	<% @ingredients.each do |ingredient| %>
	<tr>
		<td><%= ingredient.name %></td>
		<td><%= link_to "Edit", edit_ingredient_path(ingredient) %></td>
		<td><%= link_to "Delete", delete_ingredient_path(ingredient), :method => :delete, :confirm => "Are you sure?" %></td>
	</tr>
	<% end %>
</table>