config/routes.rb
CrServer::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users

  root :to => "ingredients#index"
  match "/d", to: "ingredients#index"
  match "/api", to: "api_documentation#index"
  
  resources :landing, only: [:index] do
    collection do
      post :signup
    end
  end

  devise_for :users

  resources :labels, only: [:create, :show] do
    member do
      put 'rate'
    end
  end

  resources :ingredients, only: [:index, :show, :edit, :update] do
    collection do
      get 'search'
      get 'proofread'
      get 'unwritten'
    end

    member do
      delete 'delete'
      put 'proof'
    end
  end

  resources :ingredient_of_the_weeks, only: [:index] do
    collection do
      get 'current'
    end
    member do
      put 'distribute'
    end
  end

  resources :resources, only: [:index] do
    member do
      get 'edit_ingredient'
      put 'update_ingredient'
    end
  end

  match "/sitemap.:format" => 'sitemap#sitemap'

  match '*path' => 'ingredients#index'

end

app/views/resources/edit_ingredient.html.erb
<h1>Edit Ingredients</h1>
<%= link_to "Resources", resources_path %>

<p><%= @resource.name %></p>
<p><%= link_to @resource.url %></p>

<%= form_tag(update_ingredient_resource_path(@resource), method: :put) do %>
  <div class="form-group">
  <%= text_area_tag :ingredients_csv, @resource.ingredient_csv, class: "form-control", rows: "3" %>
  </div>
  <%= submit_tag "Update", class: 'btn' %>

<% end %>

app/views/resources/index.html.erb
<h1>Resources</h1>

<table class='table'>
  <% @resources.each do |resource| %>
    <tr>
      <td><%= resource.type %></td>
      <td><%= resource.name %></td>
      <td><%= resource.url %></td>
      <td><%= link_to "Edit Ingredients", edit_ingredient_resource_path(resource) %></td>
    </tr>
  <% end %>
</table>